### ISSUE TITLE
remove button doesn't work

### ISSUE THREAD

**Issue by anonymouse64** [canonical-websites/build.snapcraft.io#1211] opened 2019-04-01 18:21 UTC
## Summary

Clicking the "trash can" icon for a linked repo to delete it brings up submenu to remove the repo, but the subsequent "remove" button doesn't do anything.

See the attached screenshot. The red button doesn't do anything when clicked.

## Process

1. Attempt to delete the repo by clicking the trashcan icon
2. Click "remove" to confirm deletion

## Current and expected result

I expected to be able to delete the repo and have it go away. It is still there and the UI does nothing when the remove button is clicked.

## Screenshot

![remove button](https://user-images.githubusercontent.com/6006573/55350050-c938ca00-5480-11e9-8812-455655448745.png)

**Comment by bartaz** [comment] 2019-04-03 08:52
Thanks for the report.
Remove functionality works (although sometimes can be a bit slow).

If you still have issues removing this specific repo there may be some problem with this specific snap.
Do you see any errors in browser console when trying to remove it?

We are also having an issue affecting some snaps where removing repo timeouts (#1176), so this may be a case for your repo as well.

**Comment by anonymouse64** [comment] 2019-04-03 11:09
I've tried multiple times and still cannot delete it, so I don't think it's just being slow to do the operation.
I will check to see if there is anything in the browser console when attempting to delete this

**Comment by bartaz** [comment] 2019-04-03 11:59
@anonymouse64 Thanks.

If this happens to be an issue I may try to remove the repo directly via API (not through UI).
I just need you to confirm which repo you want removed. Is this https://github.com/anonymouse64/edgex-core-snap?

This still may not work if it's affected by issue mentioned in #1176, but we may at least give it a try

**Comment by anonymouse64** [comment] 2019-04-03 12:10
Yes that is the correct repo to remove

**Comment by bartaz** [comment] 2019-04-03 12:20
Ok, I'll try to do it later today.

**Comment by bartaz** [comment] 2019-04-03 14:38
Sorry, it seems that your repo is in fact affected by the same problem we've seen before and that wasn't fixed yet. This prevents us from being able to change or remove it via API.

I commented on original issue in our build backend (https://bugs.launchpad.net/launchpad/+bug/1803163) to hopefully bring some attention back to it.

I'll close this for now, as it's clearly a duplicate of #1176, but feel free to comment here if you have any questions.

Sorry for the problem.

**Closed by bartaz** 2019-04-03 14:38 UTC
