### ISSUE TITLE
[repo details] Latest build component

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#348] opened 2017-03-03 22:46 UTC
Currently we simply list all previous builds.

We don't have a separate component for showing one latest build.

---

Copied from Trello card: https://trello.com/c/NEZjApGb/147-repo-details-latest-build-component
Labels:

**Comment by matthewpaulthomas** [comment] 2017-06-09 13:44
Duplicate of (more specific) #671.

**Closed by matthewpaulthomas** 2017-06-09 13:44 UTC
Labels: Status: Triaged
