### ISSUE TITLE
builder should download all repo submodules

### ISSUE THREAD

**Issue by benapetr** [canonical-websites/build.snapcraft.io#886] opened 2017-07-14 12:18 UTC
## Summary

Right now it doesn't seem to be possible to build any project with submodules as they aren't automatically downloaded together with repository

## Process

Try to build some project on github that uses submodules that are necessary build dependency

## Current and expected result

Builder should download all submodules so that builds work

There is very ugly workaround where repo is downloaded again using snapcrafts git type of source, that way it downloads the submodules, but this way it's not bound to certain revision. Pushing 2 revisions in same moment would result in 2 separate build that would both download HEAD, so it's really messy, but probably only way to fix this.

**Comment by cjwatson** [comment] 2017-07-14 12:52
Duplicate of https://bugs.launchpad.net/launchpad-buildd/+bug/1694413, and there's already a merge proposal awaiting review there.

**Closed by cjwatson** 2017-07-14 12:52 UTC
