### ISSUE TITLE
Honour repository default branch setting [2]

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#497] opened 2017-03-15 17:01 UTC
I have a project at https://github.com/popey/home-assistant yaml at https://github.com/popey/home-assistant/blob/dev/snap/snapcraft.yaml - tried hooking it up to build.s.i and got 
"Could not find snap/snapcraft.yaml. Are you sure you're in the right directory?"
https://build.snapcraft.io/popey/home-assistant/builds/27893

**Comment by cjwatson** [comment] 2017-03-15 17:12
This is because we hardcode the `master` branch at present.  This is almost a duplicate of #440, except that this issue also exposes the fact that in this case the repository's default branch is set to `dev` rather than `master`, and we should honour that as the default even once we allow branch selection.

**Comment by evandandrea** [comment] 2017-04-23 21:53
I'm bumping this down in priority some, but not yet dropping it from GA. I did a quick scan of the trending repositories on GitHub and not a single one used something other than master for the default branch.

**Comment by cjwatson** [comment] 2017-05-03 22:57
My inclination for this is to change Launchpad to allow passing `HEAD` as the `git_path` for a snap to indicate the default branch, which would be more or less consistent with the behaviour of `git` itself.  We can then change the hardcoded `refs/heads/master` in BSI to be `HEAD` instead.

**Comment by cjwatson** [comment] 2017-05-04 10:29
https://bugs.launchpad.net/bugs/1688224

**Comment by elopio** [comment] 2017-06-13 23:09
This affects https://github.com/ethereum/cpp-ethereum
It's failing to build because it has develop as the default branch, with the snapcraft.yaml. Master hasn't been touched in a long time.

**Closed** 2017-07-20 12:09 UTC

**Comment by elopio** [comment] 2017-07-20 17:12
Thanks a lot for the fix @cjwatson!

Is there something to do in the existing builds? cpp-ethereum is still failing: https://launchpad.net/~build.snapcraft.io/+snap/6d3df757960b94b20e2665180ef14f58-xenial

**Comment by cjwatson** [comment] 2017-07-20 22:52
@elopio The fix is in master but not rolled out yet.  That'll happen in due course.  We'll probably also need to look at existing snaps and update them where necessary.

**Comment by evandandrea** [comment] 2017-07-31 21:49
Thanks for fixing this. I just noticed https://build.snapcraft.io/user/ovilab/atomify is affected.

Is this still working its way to production? May we have a rollout this week?
