### ISSUE TITLE
Allow adding snaps that you are a collaborator for

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#843] opened 2017-06-20 13:29 UTC
In user testing Blake tried to add the maas snap to build.snapcraft.io, which is owned by the maas LP user. Blake is a collaborator on this snap, but it told him that he didn't have permission to add it.

**Comment by cjwatson** [comment] 2017-06-20 13:43
Do you have the exact error message?  Do you know at exactly which stage it failed?

**Comment by bartaz** [comment] 2017-06-20 13:54
My guess would be that name registration failed (if name is owned by maas user and was attempted to be added by other user), as that's the first point where we do any permissions checks with the store.

Unless it was a problem with some GH permissions (only GH admins can add repos).

**Comment by cjwatson** [comment] 2017-06-20 14:05
Those were also my guesses, but it would save much time going down blind alleys to have the exact error message, which would disambiguate.

**Comment by evandandrea** [comment] 2017-06-20 14:06
Yes, sorry. It was a failure in the name registration box. I don't recall the exact message, but I believe it was "Sorry, that name is already taken"

**Comment by Saviq** [comment] 2017-08-04 16:48
Here's a screenshot of the message I got in the exact same situation for `mir-kiosk-apps`

![Screenshot](https://user-images.githubusercontent.com/231077/28978202-5e3efbe2-7945-11e7-8389-e598d7ec1cca.png)

**Comment by adglkh** [comment] 2017-08-15 05:48
Same here. 
We're in a transition towards migrating some snaps build from launchpad to build.snapcraft.io.
I am a collaborator of easy-openvpn project.
When I added the repo and clicked "Register name", error pop-ups.
![1](https://user-images.githubusercontent.com/4225923/29303392-045cb0f6-81bf-11e7-9635-57356808dc46.png)

This issue probably will be going to be a major setback for developers who use build.snapcraft.io to build & publish snap into a store, especially for a large project which has a bunch of developers to contribute.
I didn't stumble upon by this issue on launchpad when building&publishing snap on it as a collaborator.

**Comment by bartaz** [comment] 2017-11-06 13:25
Duplicate of #799

**Closed by bartaz** 2017-11-06 13:25 UTC
Labels: promo-worthy
