### ISSUE TITLE
previously configured repo now missing in my build service dashboard

### ISSUE THREAD

**Issue by diddledan** [canonical-websites/build.snapcraft.io#1175] opened 2018-11-20 10:55 UTC
## Summary

My dashboard no-longer shows my repo [diddlesnaps/M.A.R.S.](https://github.com/diddlesnaps/M.A.R.S.) This repo was previously correctly visible and performing builds. I cannot re-add the repo because the browser sits doing nothing when I try.

## Process

No idea what the cause is, or how to reproduce. If you can log-into the dashboard as me, then you can see that the repo is missing, and that you cannot re-add the repo (it should be linked to the snap called [marsshooter](https://snapcraft.io/marsshooter))

## Current and expected result

- The repo is not visible.
- The repo should be visible and allow manual build triggers.

## Screenshot

Attempting to re-add the repo results in a situation similar to #1155 with an identical log message in the browser console:

![image](https://user-images.githubusercontent.com/147548/48769030-8553de00-ecb2-11e8-8bbe-1a9b4119ea12.png)

![image](https://user-images.githubusercontent.com/147548/48769055-9997db00-ecb2-11e8-9ff2-4fb170ae71c5.png)

**Comment by diddledan** [comment] 2019-02-01 16:42
Also missing is tvheadend.

**Comment by diddledan** [comment] 2019-02-01 16:50
well by jingo just as I hit reload they've all magically appeared. did a release to fix #1181 rollout recently that I didn't get until I forced the refresh?

**Comment by bartaz** [comment] 2019-02-04 07:57
The issue was not yet fixed.
My guess is that refresh helped due to our serverside caching. Repositories requested on the first page load have beed cached, so the second page load requested another batch (consisting missing repos).

As this issue seems clearly like a duplicate of #1181, I'll close it to track it in one place.

**Closed by bartaz** 2019-02-04 07:57 UTC
