### ISSUE TITLE
No way to retrigger a build when failing

### ISSUE THREAD

**Issue by didrocks** [canonical-websites/build.snapcraft.io#901] opened 2017-07-25 06:00 UTC
Some failures may be intermittent, or due to snapcraft itself like https://build.snapcraft.io/user/ubuntu/ubuntu-make/59531

/build/aaa1e56d8834e914e19941f0fee11c2b-xenial/parts/umake/install/usr/bin/python3 setup.py --no-user-cfg install --single-version-externally-managed --user --record install.txt
[Errno 1] Operation not permitted: '/build/aaa1e56d8834e914e19941f0fee11c2b-xenial/parts/umake/install/lib64/ld-linux-x86-64.so.2'

The previous build with the exact same code (but different README.md) worked. I was expecting to be able to reschedule a build without needed to commit to master.
Right now, the only way is a dummy commit to the tracked branch.

**Comment by cjwatson** [comment] 2017-07-25 09:51
Duplicate of #770.

**Closed by cjwatson** 2017-07-25 09:51 UTC
