### ISSUE TITLE
"Report a bug on this site" links to wrong place - really minor bug

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#981] opened 2017-10-25 10:40 UTC
## Summary

Discover a bug in build.snapcraft.io, scroll to the bottom to find the 'report a bug' link. Find link goes to wrong place in github. It redirects, but it's still wrong.

## Process

Go to build.snapcraft.io
Scroll down
Click the "Report a bug on this site" link
Note the url goes to a github project canonical-ols
Click it

## Current and expected result

Went to https://github.com/canonical-ols/build.snapcraft.io/issues/new 
Got redirected to https://github.com/canonical-websites/build.snapcraft.io/issues/new

Maybe just link to the right place rather than bounce off the wrong place?

**Comment by cjwatson** [comment] 2017-10-25 10:53
Duplicate of #806.

**Closed by cjwatson** 2017-10-25 10:53 UTC
