### ISSUE TITLE
The "Not configured" and "Not registered" links feel weird

### ISSUE THREAD

**Issue by nataliabidart** [canonical-websites/build.snapcraft.io#630] opened 2017-04-12 15:11 UTC
Being my first time at BSI, I saw the links-alike option "Not configured" and "Not registered" and clicked on each one hoping they will guide me to do the proper configuration and the proper registration, but instead I got a weird "page movement": the page scrolled up and down in an instant and after feeling nothing happened and that the link were faked, I noticed that the help text was shown/hidden which each click.

Personally, I don't think the "Not configured" and "Not registered" legends should be shown as links if you can't click them and be assisted to do configuring and registering, and even if the are shown as links, I don't think clicking on them should move the page up and down because it makes the user confused and dizzy.

Is worth noting that I can't reproduce every time, it happens usually after initial landing in the repo list page.

**Comment by matthewpaulthomas** [comment] 2017-04-12 15:30
It is always the case that you can click “Not configured” or “Not registered” and be assisted in doing the configuring and registering. In the “Not configured” case, you may have interpreted that assistance as mere “help text” because it doesn’t include form fields, though it includes a link to a form on GitHub.

So I think there are four distinct issues here:
- In the long run, clicking any “Configured” column cell should reveal a form for editing snapcraft.yaml (#390)
- In the meantime, if many people do not notice the “Get started with a template” link, maybe it should be a button instead.
- Arguably, cells that expand when clicking (“Configured” and “Registered for publishing“) should be styled differently from cells that go to a different page when clicking (“Name” and “Latest build”). (@jamiedawsonyoung and I have discussed this.)
- The page certainly shouldn’t jump up and down, and doesn’t for me. What browser version are you using? Perhaps you could attach a cropped screencast?

**Comment by nataliabidart** [comment] 2017-04-12 16:30
Hi Matthew,

I'm using Firefox 52.0.2 (64-bit) on Ubuntu. I recorded a short video about the issue (please do not share publicly nowhere outside canonical VPN):

https://private-fileshare.canonical.com/~nessita/weird-scroll.ogv

As you can see when I scroll down to the bottom to see my repos, clicking on a link that is "inviting" me to continue just makes everything "from above" come down (because of the hidden row), but to the eyes of a normal user that feels like a glicth.

I don't understand why we would want to hide the help (and then move the visible world for the user) when clicking on what it looks like "an action".

**Comment by matthewpaulthomas** [comment] 2017-04-13 09:50
Thank you for the screencast; now I understand what happened.

When you add your first repo, we (a) suggest that you register a name for it and (b) auto-expand the panel for registering the name. Unfortunately, the visual design of the table row did not make it clear enough that we’d auto-expanded the panel: it could easily be seen as an unrelated table row, especially if you’re in a hurry. (This was exacerbated by the panel not containing a text field, because you have to sign in to Ubuntu One before you get to the text field.)

So you clicked the “Not registered” cell, expecting it to produce UI for registering the name, but instead it _collapsed_ the already-open UI for registering the name. This made the page as a whole shorter, and because you were at the bottom of the page, this caused everything above to jump downward.

So I think this is a duplicate of #321: making the expanded panel more obviously related to the relevant cell (and adding expand/collapse arrows to each expandable cell) should make it more obvious that the registration UI is already open.

**Comment by matthewpaulthomas** [comment] 2017-11-06 13:18
As I described above, this is a duplicate of #321, which is now fixed. That the links don’t look very clickable in the first place is #764.

**Closed by matthewpaulthomas** 2017-11-06 13:18 UTC
