### ISSUE TITLE
Regression: repo pages no longer public

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#1149] opened 2018-09-18 12:18 UTC
## Summary

Directly visiting a repo page redirects you to snapcraft.io rather than showing you the repo page. These should be visible without needing to log in.

## Process

* Go to https://build.snapcraft.io/user/heroku/cli

## Current and expected result

* You are redirected to https://snapcraft.io
* You should instead see https://build.snapcraft.io/user/heroku/cli, regardless of whether you are logged in

## Screenshot

![no-public-build-page](https://user-images.githubusercontent.com/1523179/45686891-92870c00-bb4d-11e8-8128-6da4e5e0b392.gif)

**Comment by cjwatson** [comment] 2018-09-18 12:54
Duplicate of #1148.

**Closed by cjwatson** 2018-09-18 12:54 UTC
