### ISSUE TITLE
Should provide more detail about "snapcraft.yaml cannot be used because it isn't valid"

### ISSUE THREAD

**Issue by diddledan** [canonical-websites/build.snapcraft.io#943] opened 2017-09-04 13:48 UTC
## Summary

[reference discussion on snapcraft forums](https://forum.snapcraft.io/t/build-service-snapcraft-yaml-can-t-be-used-because-it-isn-t-valid/1958)

As shown in the screenshot, when the service detects a problem it does not tell the user what that problem is and thus the user is unable to form a plan to fix it.

Relevant quotes from the thread on forum.snapcraft.io:

> The build service needs to be more verbose when explaining that a build is broken because “snapcraft.yaml can’t be used because it isn’t valid”. It needs to tell us what it thinks is not valid or else how are we supposed to figure out what to change? This is particularly true when, as in the case of Corebird, the snapcraft.yaml works perfectly fine under snapcraft cleanbuild locally indicating that something is wrong with the build service but because it won’t tell us what it thinks is broken we can’t determine where the problem lies.

> No matter what the reason, this is a pretty strange message to have in the first place. Any code that checks for validity of the file should fail saying what was wrong, of course.

A relevant change was made in PR #899 

## Process

1. Provide an invalid snapcraft.yaml via a connected repository.
2. View the screen showing the status of the build

## Current and expected result

Current:
It says "The snapcraft.yaml cannot be used because it isn't valid" ([source for that message]( https://github.com/canonical-websites/build.snapcraft.io/blob/be1bd2d8b0459d7f2e154971e77bd54d19ab5b10/src/common/components/repository-row/dropdowns/configuration-error-dropdown.js#L36]))

Expected:
A message should detail what the problem was so that the user can fix it.

## Screenshot

![screenshot from 2017-09-03 18-28-38](https://user-images.githubusercontent.com/147548/30029009-50b076fc-917f-11e7-8c35-7253b47336c1.png)

**Comment by matthewpaulthomas** [comment] 2017-09-05 09:48
Thanks for the report. This is a duplicate of #668.

**Closed by matthewpaulthomas** 2017-09-05 09:48 UTC

**Comment by bartaz** [comment] 2017-09-05 10:31
@diddledan I've run your yaml through the same linter that is used in BSI and this is the error it found:

```
YAMLException: duplicated mapping key at line 12, column 14:
    grade: stable
                 ^
```

But of course we should be showing this to the users and we have that feature in our backlog.
