### ISSUE TITLE
can't run the server

### ISSUE THREAD

**Issue by theshadowx** [canonical-websites/build.snapcraft.io#700] opened 2017-04-29 13:39 UTC
when running the server as mentioned in README : 
```
> npm start
```

I receive this error message : 

```
/build.snapcraft.io/webpack/webpack-dev-server.js:9
const { conf } = require('../src/server/helpers/config');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

so I have removed "{}"  from line 9 and use directly the conf from config.js : 
```
const conf = require('../src/server/helpers/config').conf;
``` 

it worked

```
Using environment: development
Already up to date
webpack: wait until bundle finished: 
2017-04-29 13:37:10.091Z INFO webpack "WebPack development server listening on http://127.0.0.1:8001" 
webpack built 5b569ef462e152413e1f in 42397ms
Hash: 5b569ef462e152413e1f
Version: webpack 1.15.0
Time: 42397ms
                                     Asset       Size  Chunks             Chunk Names
icons/cb5050eec6b490b106febed3ce32af77.svg     5.9 kB          [emitted]  
icons/ba3fd6fbbc639378c2e6f37f43cb812c.svg    7.75 kB          [emitted]  
icons/c3015ff051a11c71c6d052c1aa732cd6.svg  167 bytes          [emitted]  
icons/f54f6a4529b28f3b93b12a557d3f3322.svg  290 bytes          [emitted]  
icons/8a3b6d4fda7be185709310fda2d7b5f5.svg    2.34 kB          [emitted]  
icons/e3ed98c9effa5cd78070162c1b4e0c35.svg     110 kB          [emitted]  
icons/a6a4a35bc9f44ef5eef40a239fa49214.svg    4.03 kB          [emitted]  
icons/783563f2f052305ae3ef604a5a0a5f01.svg    3.29 kB          [emitted]  
icons/8071d37fd54902d051bc4e71d5dfc93d.svg  775 bytes          [emitted]  
icons/c60c30d78649f2775c78e01eed78676f.svg    1.24 kB          [emitted]  
icons/dbe04dd9b6ecdde31e02fd6617e5c649.svg    4.08 kB          [emitted]  
icons/d48f3adfb2f375147da21922f104bc1b.svg    3.15 kB          [emitted]  
                                 bundle.js    3.37 MB       0  [emitted]  main
                                 style.css    40.4 kB       0  [emitted]  main
                             bundle.js.map    3.85 MB       0  [emitted]  main
                             style.css.map   86 bytes       0  [emitted]  main
webpack: Compiled successfully.
29 Apr 13:38:19 - Missing './version-info.txt', cannot set correct X-VCS-revision header
2017-04-29 13:38:19.884Z INFO session "Starting with development default session secret" 
2017-04-29 13:38:19.969Z INFO express "Express server listening on http://0.0.0.0:8000" 

```

**Comment by nottrobin** [comment] 2017-05-19 14:44
Hi @theshadowx. Thanks for filing this. The installation instructions in the README are somewhat out of date, and we're planning to start looking into them and make sure they're in good shape next week. We'll try to look into this issue then and update you here.

**Comment by nottrobin** [comment] 2017-06-21 14:50
We can't reproduce this (see #805). We'll close it for now hoping it's fixed. @theshadowx please file another issue if you still encounter problems.

**Closed by nottrobin** 2017-06-21 14:50 UTC
