### ISSUE TITLE
Can't see any repos in BSI if repo was removed from GitHub

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#968] opened 2017-10-05 09:09 UTC
## Summary

Found then debugging #925 and quite likely being the main cause of the issues of @kz6fittycent
If user removes from GitHub any repos previously added to BSI, BSI will fail to show ANY repos to this user simply showing empty ("No repos") My repos page.
Any attempt to add repos again will fail, because there repos exist on Launchpad but are not displayed to the user due to this bug.

## Process

1. Have some dummy repository on GH
2. Add this dummy repo to BSI (also have other repos added to BSI)
3. Remove dummy repo from GH
4. Refresh My repos page
5. No repos will be shown

In browser console API call to list snaps returns with 404:
http://localhost:8000/api/launchpad/snaps/list?owner=bartaz
`{"status":"error","payload":{"code":"github-snapcraft-yaml-not-found","message":"Cannot find snapcraft.yaml in this GitHub repository"}}`

Currently the only way to workaround this issue is manually removing repository from Launchpad.

## Expected

If repos were removed from GH they should simply be ignored (not throw an error).
They should appear on the repos list in BSI (because they still exist in Launchpad) and user should be able to remove (from BSI) on their will.

## Screenshot

<img width="1044" alt="screen shot 2017-10-05 at 11 05 16" src="https://user-images.githubusercontent.com/83575/31219437-9bd3933e-a9bd-11e7-8fe4-73d5577bd41e.png">

**Comment by matthewpaulthomas** [comment] 2017-10-06 08:18
This looks like a duplicate of #453.

**Comment by bartaz** [comment] 2017-10-06 08:34
@matthewpaulthomas It certainly has similar effect, although it says about removing repo from BSI that was removed from GH - which makes it seem like the repo was visible in BSI. But the app changed quite a lot since March so the cause of the bug may be different. 

Especially that we had later cases where people would not be able to remove repos that were removed from GH, but they've seen them on the list: #859 
So this one is a regression that was introduced recently. I think we can safely close #453

Right now removing repo from GH makes all repos dissapear from BSI UI - which is much more serious.

**Closed** 2017-10-12 08:13 UTC
Labels: Priority: High, Type: Bug
