### ISSUE TITLE
Can't remove repo that was removed from GitHub

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#859] opened 2017-06-29 08:53 UTC
## Summary

I have a repo in my b.s.i list *(that was removed from GH)* and when I hit the red remove button, nothing happens.

## Process

*Add a repo to BSI, go to GitHub and remove this repo from GitHub, go back to BSI.*

Login, try click trash icon, click sign in (for some reason), click remove red button.

## Current and expected result

It should be removed. Others can be removed, home-assistant cannot.

## Screenshot

![image](https://user-images.githubusercontent.com/1841272/27679466-bc746ca8-5cb0-11e7-8e74-640125056ea1.png)

**Comment by bartaz** [comment] 2017-06-29 09:05
Can you have a look into browser console and see if there are any errors there after you click Remove? JavaScript errors, or some errors in responses from APIs?

**Comment by popey** [comment] 2017-06-29 09:14
VM241:1 POST https://build.snapcraft.io/api/launchpad/snaps/delete 404 (Not Found)

**Comment by bartaz** [comment] 2017-06-29 09:24
@popey That would suggest that the snap for this repo doesn't exist (anymore), but then it should not appear on the list...

If you refresh the page or sign in again it's still there?

**Comment by popey** [comment] 2017-06-29 09:26
I have tried refreshing, signing out and in and it still won't disappear.

**Comment by bartaz** [comment] 2017-06-29 09:28
@popey OK, thanks for confirmation. Can you have a look into response body of this 404? Maybe an error message will give us more context.

**Comment by popey** [comment] 2017-06-29 09:49
is this what you're after?

"{"status":"error","payload":{"code":"github-snapcraft-yaml-not-found","message":"Cannot find snapcraft.yaml in this GitHub repository"}}"

![image](https://user-images.githubusercontent.com/1841272/27681909-a4e5302e-5cb8-11e7-9761-20ff8c10c8be.png)

**Comment by bartaz** [comment] 2017-06-29 09:54
@popey Yes, thanks. 

Missing snapcraft.yaml is not what I would expect to see here - it shouldn't matter if repo has snapcraft.yaml to remove it. Would need to investigate more why this may happen. But that's a useful clue, thanks!

**Comment by bartaz** [comment] 2017-06-29 10:01
@popey This repo doesn't seem to be public on GH (anymore)? https://github.com/popey/home-assistant

Of course it's a bug on our side that we require GH repo to exist to remove it from the list, but I guess that's the case. We are trying to check if you have admin permissions for this repo, but we fail to find it in GH.

I'm not sure if we should ignore this check and allow to remove repos you are not admin of, but I guess if repo doesn't exist on GH we should just remove it.

**Comment by popey** [comment] 2017-06-29 10:10
@bartaz  Yeah, I deleted the repo on github at some point. I expected the site to allow me to remove it given it doesn't exist on GH anymore.

**Comment by bartaz** [comment] 2017-06-29 10:23
@popey Yes, I think that would be the expected behaviour, we need to fix that.

**Comment by popey** [comment] 2017-06-29 10:27
Can someone ninja edit it out of my repo for now? I'm giving a talk later and wanted a nice tidy UI :)

**Comment by bartaz** [comment] 2017-06-29 10:57
@popey should be all clear now

**Comment by matthewpaulthomas** [comment] 2017-07-09 17:23
Duplicate of #398.

**Closed by matthewpaulthomas** 2017-07-09 17:23 UTC
Labels: Type: Bug
