### ISSUE TITLE
Build.snapcraft.io empty… Can´t add my snaps/repos to it 

### ISSUE THREAD

**Issue by abacao** [canonical-websites/build.snapcraft.io#974] opened 2017-10-10 17:39 UTC
I already had 2 snaps in build.snapcraft.io1.

My snapcraft is empty and I’m not able to add again my repos (forever loading)

Javascript console here: link [link](https://pastebin.com/U4URJ2Je)

Pic with failed GET
![build_failed](https://user-images.githubusercontent.com/17479246/31401233-39a6143a-adea-11e7-8c0c-85211325ebc1.png)

More info here: https://forum.snapcraft.io/t/build-snapcraft-io-empty-can-t-add-my-snaps-repos-to-it/2251

**Comment by bartaz** [comment] 2017-10-10 19:05
@abacao This seems like a duplicate of #974

Have you recently removed any GH repo (previously added to BSI)? Or made it private?

**Comment by abacao** [comment] 2017-10-10 19:32
Hi, i AM 99% sure i didn't. I had already created a issue in the forum but Evan told me to add it here.
In the forum there is another user providing more information about it.

PS- I started to use buildcraft still in beta

**Comment by kz6fittycent** [comment] 2017-10-10 23:09
Here’s the output from my browser for anyone who wants it:

`2api/launchpad/snaps/list?owner=kz6fittycent Failed to load resource: the server responded with a status of 404 (Not Found)
api/launchpad/snaps Failed to load resource: the server responded with a status of 400 (Bad Request)
bundle.9c7c5495b89e55eca027.js:25 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at https://build.snapcraft.io/static/bundle.9c7c5495b89e55eca027.js:25:3477
    at o (https://build.snapcraft.io/static/bundle.9c7c5495b89e55eca027.js:73:24544)
    at Generator._invoke (https://build.snapcraft.io/static/bundle.9c7c5495b89e55eca027.js:73:25946)
    at Generator.e.(anonymous function) [as throw] (https://build.snapcraft.io/static/bundle.9c7c5495b89e55eca027.js:73:24723)
    at n (https://build.snapcraft.io/static/bundle.9c7c5495b89e55eca027.js:25:2610)
    at https://build.snapcraft.io/static/bundle.9c7c5495b89e55eca027.js:25:2735
    at <anonymous>
api/launchpad/snaps Failed to load resource: the server responded with a status of 400 (Bad Request)`


AND:

`{"status":"error","payload":{"code":"lp-error","message":"url: Required input is missing."}}`

**Comment by bartaz** [comment] 2017-10-11 06:31
@abacao I found 3 repos registered for your user:
https://github.com/abacao/packer-snap
https://github.com/abacao/nextcloud-snap (returns 404)
https://github.com/abacao/terraform-snap

If you are fine with that we can remove https://github.com/abacao/nextcloud-snap manually (meaning that build history will be lost) which should fix the issue for you (until we have a proper fix for #974 released).

**Comment by abacao** [comment] 2017-10-11 09:25
Hi @bartaz, with that information I was able to re-create the repo, delete from build.snapcraft.io and everything is fine.

Is there a way that a user can see exactly the repos that are registered to help sort this issue?

**Comment by bartaz** [comment] 2017-10-12 13:10
Fixed by #973

**Closed by bartaz** 2017-10-12 13:10 UTC
