### ISSUE TITLE
Show repos with an invalid snapcraft.yaml as "Error" instead of "Not configured" [1]

### ISSUE THREAD

**Issue by noise** [canonical-websites/build.snapcraft.io#548] opened 2017-03-27 18:24 UTC
Similar to: https://github.com/canonical-ols/build.snapcraft.io/issues/293

I'm trying to add my repo https://github.com/noise/stegocaps, followed the "get started with template" path, which yielded:
  https://github.com/noise/stegocaps/blob/master/snap/snapcraft.yaml

but even after page reload, it's still not finding my repo as "configured". I also tried adding a .snapcraft symlink at the base of the repo but no luck.

**Comment by evandandrea** [comment] 2017-03-28 07:33
I can confirm this by forking stegocaps from @noise and trying to add it myself. No errors are returned.

**Comment by bartaz** [comment] 2017-04-03 11:54
@noise @ev This repo contains invalid snapcraft.yaml file. Line 16 indent is invalid: https://github.com/noise/stegocaps/blob/master/snap/snapcraft.yaml#L16

We currently don't show validation errors for snapcraft.yaml - invalid file shows simply as not configured (same as missing file), which obviously leads to some confusion.

Design spec doc defines a state for invalid snapcraft.yaml but it's marked as "TBD" stretch goal: https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.j4z5b2pn5rsf

To avoid such confusion it would be best to at least tell users that file is invalid.

**Comment by evandandrea** [comment] 2017-04-03 12:33
Thanks @bartaz. Moved to GA and retitled for handling the invalid snapcraft.yaml case.

**Comment by evandandrea** [comment] 2017-04-21 12:50
@bartaz pointed out that we could do a very basic yaml syntax check cheaply. So let's do that, not any kind of complex validation of whether snapcraft will succeed given the snapcraft.yaml.

**Comment by bartaz** [comment] 2017-04-21 13:14
We use https://github.com/nodeca/js-yaml library to parse contents of snapcraft.yaml, so if there is a YAML parsing error they detect we can show it to user.

By default error messages are formatted an in these examples:

```
duplicated mapping key at line 4, column 13:
    name: test-1
                ^
```

```
bad indentation of a mapping entry at line 3, column 7:
      icon: invalid-indent.png
          ^
```

This seems to assume fixed width font (like a console output) to properly format positioning of `^` arrow pointing at specific character where error is detected.

If we want more flexibility it seems we can access just the text explanation of the reason, like "bad indentation of a mapping entry" and line/column numbers.

Please note that we don't really control the text of these messages, so if explanation of the error is not very user friendly we can't really change that.

**Comment by evandandrea** [comment] 2017-04-22 20:03
I think we should just start with "Error" if it can't parse and have a follow on GitHub issue for showing more of the error message. But let's wait for @matthewpaulthomas to weigh in.

**Comment by evandandrea** [comment] 2017-05-15 14:13
Should also include checking for required by snapcraft fields, such as name (#548).

**Closed** 2017-07-25 13:11 UTC
Labels: Design: In progress
