### ISSUE TITLE
In-table form is visually split

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-websites/build.snapcraft.io#1002] opened 2017-11-06 15:27 UTC
## Summary

In the user page, the form to register a name is split into two parts, and the text field can be missed.

The dropdown for an existing snap name does not appear to have this problem.

## Process

- Go to user page with an unregistered snap
- Click "Not registered"

## Current and expected result

The dropdown does not connect with the button and looks visually separate.

## Screenshot

![selection_011](https://user-images.githubusercontent.com/322693/32448296-76ba076a-c306-11e7-8b4a-cc0a3fc03b08.png)

**Comment by matthewpaulthomas** [comment] 2017-11-06 16:26
Duplicate of #793.

**Closed by matthewpaulthomas** 2017-11-06 16:26 UTC
