### ISSUE TITLE
build.snapcraft.io doesn’t mention any other way of building snaps

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#991] opened 2017-10-30 15:47 UTC
If you hadn’t heard anything about snaps, if you read through [the build.snapcraft.io front page](https://build.snapcraft.io/), you would undoubtedly get the impression that auto-building from GitHub is the only way to build snaps.

Eventually this will be solved by an integrated snapcraft.io. But in the meantime, we could add a quick link below the big green buttons. Something like:

> (Private project, or code’s not on GitHub? Try [building a snap on your own system](https://docs.snapcraft.io/build-snaps/) instead.)

**Comment by Lukewh** [comment] 2017-11-06 11:34
Duplicate of https://github.com/canonical-websites/build.snapcraft.io/issues/794

**Closed by Lukewh** 2017-11-06 11:34 UTC
Labels: Priority: Medium
